require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rails
  - rubocop-factory_bot

AllCops:
  Exclude:
    - 'bin/*'
    - 'db/**/*'
    - 'node_modules/**/*'
  NewCops: enable

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 1500

Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/SymbolArray:
  Enabled: true

# Most readable form.
Layout/HashAlignment:
  EnforcedHashRocketStyle: key
  EnforcedColonStyle: key

# Mixing the styles looks just silly.
Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys
  EnforcedShorthandSyntax: never

Style/CollectionMethods:
  Enabled: true
  PreferredMethods:
    reduce: 'inject'

# A specialized exception class will take one or more arguments and construct the message from it.
# So both variants make sense.
Style/RaiseArgs:
  Enabled: false

# Indenting the chained dots beneath each other is not supported by this cop,
# see https://github.com/bbatsov/rubocop/issues/1633
Layout/MultilineOperationIndentation:
  Enabled: false

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

# allow {...} for multi-line blocks
Style/BlockDelimiters:
  Enabled: false

Style/Documentation:
  Enabled: false

Naming/MethodParameterName:
  AllowedNames:
    - id

Style/IfUnlessModifier:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'config/**/*'
    - 'spec/**/*'

Rails/FilePath:
  EnforcedStyle: slashes

RSpec/NestedGroups:
  Max: 7

RSpec/ContextWording:
  Prefixes:
    - when
    - with
    - without
    - and
    - if
    - in
    - for

RSpec/ExampleLength:
  Max: 20

Layout/MultilineMethodCallIndentation:
  Enabled: false

Style/FormatStringToken:
  EnforcedStyle: template

RSpec/ImplicitSubject:
  EnforcedStyle: single_statement_only

# avoiding rubocop bug
Rails/UniqueValidationWithoutIndex:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Rails/FindEach:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/PredicateMatcher:
  Enabled: false

FactoryBot/ConsistentParenthesesStyle:
  Enabled: false

Rails/InverseOf:
  Enabled: false

Rails/RedundantForeignKey:
  Enabled: false

Naming/BlockForwarding:
  EnforcedStyle: explicit

RSpec/IndexedLet:
  Enabled: false

FactoryBot/ExcessiveCreateList:
  Enabled: false

Metrics/ParameterLists:
  Max: 6
