# frozen_string_literal: true

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 20 } %>
  host: localhost
  port: 5432

development:
  <<: *default
  database: fantasy_sports_development

test:
  <<: *default
  database: fantasy_sports_test

production:
  <<: *default
  database: fantasy_sports_production
  username: fantasy_sports
  password: <%= Rails.application.credentials[:database_password] %>
